site_name: pyjokes
theme: readthedocs
site_url: https://pythonhosted.org/pyjokes/
repo_url: https://github.com/pyjokes/pyjokes
site_description: One-line programmer jokes (jokes-as-a-service)
site_author: Pyjokes Society
site_dir: pythonhosted
